### ISSUE TITLE
Cannot use in Office Addins

### ISSUE THREAD

**Issue by dlee992** [psalaets/excel-formula-tokenizer#3]
I am developing an Office Add-in for Excel, I want to use your tokenization for some parts, but when I write down this line of code:
`const {tokenize} = require('excel-formula-tokenizer');`

then, when I debug my excel addin, it shows "Please wait your add-in to sideload", and I cannot see any button in my addin.

When I comment this line, everything is just fine. I don't know why this happened.

Here is my repo: [dlee992](github.com/dlee992/Warder-Plugin.html)

**Comment by psalaets** [comment]
Sorry I don't know anything about developing Office Add-ins.

Does it support node-style `require()` calls?
